services:
  mysql:
    image: crud-mysql:v1
    container_name: crud-mysql
    environment:
      MYSQL_DATABASE: crud_app
      MYSQL_USER: crud
      MYSQL_PASSWORD: CrudApp@1
      MYSQL_ROOT_PASSWORD: siva
    networks:
      - crud

  crud-redis:
    image: redis:7
    container_name: crud-redis
    networks:
      - crud

  crud-backend:
    image: crud-backend:v1
    container_name: crud-backend
    environment:
      DB_HOST: crud-mysql
      DB_NAME: crud_app
      DB_USER: crud
      DB_PASSWORD: CrudApp@1
      REDIS_HOST: crud-redis
      REDIS_SSL: "false"
    depends_on:
      - mysql
      - crud-redis
    restart: unless-stopped
    networks:
      - crud

  crud-frontend:
    image: crud-frontend:v1
    container_name: crud-frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - crud-backend
    restart: unless-stopped
    networks:
      - crud
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - crud
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - crud
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  crud:
    driver: bridge