services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: crud-mysql:v1

  crud-backend:
    build:
      context: ./project
      dockerfile: Dockerfile
    image: crud-backend:v1

  crud-frontend:
    build:
      context: ./crud-frontend
      dockerfile: Dockerfile
    image: crud-frontend:v1