services:
  
  crud-backend:
    image: crud-backend:v1
    container_name: crud-backend
    environment:
      DB_HOST: database-1.ctsykewmixjj.us-east-1.rds.amazonaws.com
      DB_NAME: crud_app
      DB_USER: crud
      DB_PASSWORD: CrudApp@1
      REDIS_HOST: valkey-2cvmu0.serverless.use1.cache.amazonaws.com
      REDIS_SSL: "true"
    restart: unless-stopped
    networks:
      - crud

  crud-frontend:
    image: crud-frontend:v1
    container_name: crud-frontend
    ports:
      - "80:80"
    volumes:
      - ../nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - crud-backend
    restart: unless-stopped
    networks:
      - crud
networks:
  crud:
    driver: bridge
