name: Deploy SPA app on S3

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::522814728660:role/sivaramakrishna-konka-iam-github-actions
          role-session-name: GitHubActionsTerraform
          aws-region: us-east-1

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build application
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          npm install
          npm run build

      - name: Verify API URL in build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          cd dist
          if grep -r "$VITE_API_URL" .; then
            echo "✅ API URL verified in build files."
          else
            echo "❌ API URL not found in build files!"
            exit 1
          fi

      - name: Deploy to S3
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 sync dist/ s3://$S3_BUCKET_NAME --delete
